"""Streamlit dashboard for visualizing GEX exports and images.

Usage:
    streamlit run streamlit_app.py

Features:
- Lists available tickers from `data/exports`
- Shows PNG snapshots from `img/` for the selected ticker
- Loads the latest CSV exports (surface, by_strike, by_expiration)
- Renders an interactive heatmap and a 3D scatter of the GEX surface
"""
from pathlib import Path
import time
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np


EXPORT_DIR = Path("data/exports")
IMG_DIR = Path("img")


def find_available_tickers(export_dir: Path):
    export_dir.mkdir(parents=True, exist_ok=True)
    files = list(export_dir.glob("*.csv"))
    tickers = set()
    for f in files:
        parts = f.name.split("_")
        if len(parts) > 1:
            tickers.add(parts[0])
    return sorted(tickers)


def latest_file_for(pattern: str, directory: Path):
    files = list(directory.glob(pattern))
    if not files:
        return None
    return sorted(files, key=lambda p: p.stat().st_mtime)[-1]


def load_surface_csv(path: Path):
    df = pd.read_csv(path)
    if "expiration" in df.columns:
        df["expiration"] = pd.to_datetime(df["expiration"])
    return df


def render_surface_heatmap(df: pd.DataFrame):
    if df.empty:
        st.info("No surface data to render.")
        return

    pivot = df.pivot(index="expiration", columns="strike", values="GEX")
    pivot = pivot.sort_index()
    z = pivot.fillna(0).values
    x = pivot.columns.astype(float)
    y = pivot.index.strftime("%Y-%m-%d")

    fig = px.imshow(
        z,
        x=x,
        y=y,
        aspect="auto",
        labels={"x": "Strike", "y": "Expiration", "color": "GEX (M$ / %)"},
        color_continuous_scale="RdYlBu_r",
    )
    fig.update_layout(height=600)
    st.plotly_chart(fig, use_container_width=True)


def render_surface_3d(df: pd.DataFrame):
    if df.empty:
        return
    x = df["strike"].astype(float).to_numpy()
    y = df["expiration"].astype(str).to_numpy()
    z = df["GEX"].astype(float).to_numpy()

    fig = go.Figure()
    fig.add_trace(
        go.Scatter3d(
            x=x,
            y=y,
            z=z,
            mode="markers",
            marker=dict(size=4, color=z, colorscale="Viridis", showscale=True),
        )
    )
    fig.update_layout(scene=dict(xaxis_title="Strike", yaxis_title="Expiration", zaxis_title="GEX (M$ / %)")
    )
    fig.update_layout(height=600)
    st.plotly_chart(fig, use_container_width=True)


def list_img_snapshots(ticker: str, img_dir: Path):
    if not img_dir.exists():
        return []
    return sorted(img_dir.glob(f"{ticker}_*.*"), key=lambda p: p.stat().st_mtime, reverse=True)


def main():
    st.set_page_config(page_title="GEX Dashboard", layout="wide")
    st.title("GEX Dashboard")

    # Sidebar controls and quick actions
    tickers = find_available_tickers(EXPORT_DIR)
    ticker = st.sidebar.selectbox("Ticker", options=tickers if tickers else ["SPX"], index=0)
    custom = st.sidebar.text_input("Or enter ticker manually (overrides) ", value="")
    if custom.strip():
        ticker = custom.strip().upper()

    st.sidebar.markdown("---")
    st.sidebar.write("Snapshot files come from data/exports (generated by `main.py`).")
    if st.sidebar.button("Refresh files"):
        st.experimental_rerun()

    # Plot options
    show_images = st.sidebar.checkbox("Show image snapshots", value=True)
    show_heatmap = st.sidebar.checkbox("Show heatmap", value=True)
    show_3d = st.sidebar.checkbox("Show 3D scatter", value=False)

    st.sidebar.markdown("---")
    st.sidebar.write("Export filters apply to the loaded CSV surface before plotting.")

    col1, col2 = st.columns([1, 2])

    # Left column: images and metadata
    with col1:
        st.header("Snapshots & Info")
        imgs = list_img_snapshots(ticker, IMG_DIR)
        if imgs and show_images:
            # show up to 6 images in two columns
            cols = st.columns(2)
            for i, img_path in enumerate(imgs[:6]):
                with cols[i % 2]:
                    st.image(str(img_path), caption=img_path.name, use_column_width=True)
            latest_img_time = time.ctime(imgs[0].stat().st_mtime)
            st.caption(f"Latest image: {latest_img_time}")
        else:
            st.info("No PNG snapshots found in img/ for this ticker.")

        # Show quick export metadata
        surface_path = latest_file_for(f"{ticker}_gex_surface_*.csv", EXPORT_DIR)
        if surface_path:
            st.markdown(f"**Latest surface CSV:** {surface_path.name}")
            st.caption(f"Updated: {time.ctime(surface_path.stat().st_mtime)}")
        else:
            st.info("No surface CSV found in data/exports for this ticker.")

    # Right column: interactive plots and filters
    with col2:
        st.header("Interactive exports")
        strike_path = latest_file_for(f"{ticker}_gex_by_strike_*.csv", EXPORT_DIR)
        exp_path = latest_file_for(f"{ticker}_gex_by_expiration_*.csv", EXPORT_DIR)

        if surface_path:
            df_surface = load_surface_csv(surface_path)

            # Allow filtering by expiration range and strike range
            if not df_surface.empty:
                min_date = df_surface["expiration"].min().date()
                max_date = df_surface["expiration"].max().date()
                date_range = st.slider("Expiration range", value=(min_date, max_date), min_value=min_date, max_value=max_date)

                strikes = sorted(df_surface["strike"].unique())
                s_min = int(min(strikes))
                s_max = int(max(strikes))
                strike_range = st.slider("Strike range", min_value=s_min, max_value=s_max, value=(s_min, s_max))

                # Apply filters
                df_filtered = df_surface.loc[
                    (df_surface["expiration"].dt.date >= date_range[0])
                    & (df_surface["expiration"].dt.date <= date_range[1])
                    & (df_surface["strike"] >= strike_range[0])
                    & (df_surface["strike"] <= strike_range[1])
                ]

                # Summary metrics
                total_gex_m = df_filtered["GEX"].sum()
                latest_updated = time.ctime(surface_path.stat().st_mtime)
                st.metric(label="Surface total GEX (M$)", value=f"{total_gex_m:,.1f}", delta=None)
                st.caption(f"Surface CSV last updated: {latest_updated}")

                # Download button for filtered CSV
                csv_bytes = df_filtered.to_csv(index=False).encode("utf-8")
                st.download_button("Download filtered CSV", csv_bytes, file_name=f"{ticker}_surface_filtered.csv", mime="text/csv")

                if show_heatmap:
                    st.subheader("GEX surface (heatmap)")
                    render_surface_heatmap(df_filtered)

                if show_3d:
                    st.subheader("GEX surface (3D scatter)")
                    render_surface_3d(df_filtered)
            else:
                st.info("Loaded surface CSV is empty.")
        else:
            st.info("No surface CSV found in data/exports for this ticker.")

        if strike_path:
            st.subheader("GEX by strike")
            df_strike = pd.read_csv(str(strike_path), index_col=0, parse_dates=False)
            try:
                df_strike.index = df_strike.index.astype(float)
            except Exception:
                pass
            fig = px.bar(df_strike, x=df_strike.index, y=df_strike.iloc[:, 0], labels={"x":"Strike","y":df_strike.columns[0]})
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("No gex_by_strike CSV found in data/exports for this ticker.")

        if exp_path:
            st.subheader("GEX by expiration")
            df_exp = pd.read_csv(str(exp_path), index_col=0)
            try:
                df_exp.index = pd.to_datetime(df_exp.index)
            except Exception:
                pass
            fig2 = px.bar(df_exp, x=df_exp.index, y=df_exp.iloc[:, 0], labels={"x":"Expiration","y":df_exp.columns[0]})
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.info("No gex_by_expiration CSV found in data/exports for this ticker.")


if __name__ == "__main__":
    main()
